// Byte layouts and addresses of the private_loan_v2 records (Stories 22.1, 23.1, 24.1).
// ER-only records are Borsh with no discriminator. Parity with the program is proven by
// isolated_loan/programs/private_loan_v2/codec-fixture.json, generated by a Rust test.
import { PublicKey } from "@solana/web3.js";
import { IS_LOCAL } from "../constants";
import { EarlyRepayment, type Ledger, type TermsV2 } from "../loan-math-v2";

export const PRIVATE_V2_ID = new PublicKey(process.env.NEXT_PUBLIC_PRIVATE_V2_PROGRAM_ID || "JAzy8NP6V8AGrAko8vfgrD44BDghN6eLwqB7vjuYhHNq");
/** New rooms, loans and desks use V2 only where the program is deployed and verified. */
export const PRIVATE_V2_LIVE = IS_LOCAL || process.env.NEXT_PUBLIC_PRIVATE_V2_LIVE === "1";

export const MAX_MEMBERS_V2 = 16;
export const DESK_MEMBERS = 16;
export const MAX_AUDITORS = 4;

export const ROLE_V2 = { borrower: 1, lender: 2, viewer: 4 } as const;
export const DESK_ROLE = { admin: 1, lender: 2, auditor: 4 } as const;
export const REPAYMENT_MODE = { fullTerm: 1, proRata: 2 } as const;

export const LOAN_STATUS_V2 = {
  0: "draft",
  1: "funded",
  2: "active",
  3: "repaid",
  5: "cancelled",
  6: "liquidated",
  7: "overdueLiquidated",
  8: "pricedRecovered",
  9: "terminalClaimed",
} as const;
export type LoanStatusV2 = (typeof LOAN_STATUS_V2)[keyof typeof LOAN_STATUS_V2];

const enc = new TextEncoder();
const pda = (...seeds: Uint8Array[]) => PublicKey.findProgramAddressSync(seeds, PRIVATE_V2_ID)[0];
const u32 = (n: number) => {
  const b = new Uint8Array(4);
  new DataView(b.buffer).setUint32(0, n, true);
  return b;
};
const u64 = (n: bigint) => {
  const b = new Uint8Array(8);
  new DataView(b.buffer).setBigUint64(0, n, true);
  return b;
};

export const v2Pda = {
  config: () => pda(enc.encode("config")),
  room: (creator: PublicKey, roomId: Uint8Array) => pda(enc.encode("room"), creator.toBytes(), roomId),
  roomState: (room: PublicKey) => pda(enc.encode("room-state"), room.toBytes()),
  roomThread: (room: PublicKey) => pda(enc.encode("room-thread"), room.toBytes()),
  roomLoan: (room: PublicKey, index: number) => pda(enc.encode("room-loan"), room.toBytes(), u32(index)),
  session: (room: PublicKey, key: PublicKey) => pda(enc.encode("session"), room.toBytes(), key.toBytes()),
  loan: (creator: PublicKey, nonce: bigint) => pda(enc.encode("loan"), creator.toBytes(), u64(nonce)),
  terms: (loan: PublicKey) => pda(enc.encode("loan-terms"), loan.toBytes()),
  deal: (room: PublicKey, requestIndex: number) => pda(enc.encode("room-deal"), room.toBytes(), u32(requestIndex)),
  quote: (loan: PublicKey) => pda(enc.encode("quote"), loan.toBytes()),
  receipt: (loan: PublicKey) => pda(enc.encode("receipt"), loan.toBytes()),
  pool: () => pda(enc.encode("liq-pool")),
  desk: (creator: PublicKey, deskId: Uint8Array) => pda(enc.encode("desk"), creator.toBytes(), deskId),
  deskState: (desk: PublicKey) => pda(enc.encode("desk-state"), desk.toBytes()),
  deskPolicy: (desk: PublicKey, version: number) => pda(enc.encode("desk-policy"), desk.toBytes(), u32(version)),
  deskLoan: (desk: PublicKey, seq: number) => pda(enc.encode("desk-loan"), desk.toBytes(), u32(seq)),
};

class Reader {
  o = 0;
  private v: DataView;
  constructor(private d: Uint8Array) {
    this.v = new DataView(d.buffer, d.byteOffset, d.byteLength);
  }
  u8() {
    return this.d[this.o++];
  }
  bool() {
    return this.u8() === 1;
  }
  u16() {
    const x = this.v.getUint16(this.o, true);
    this.o += 2;
    return x;
  }
  u32() {
    const x = this.v.getUint32(this.o, true);
    this.o += 4;
    return x;
  }
  u64() {
    const x = this.v.getBigUint64(this.o, true);
    this.o += 8;
    return x;
  }
  i64() {
    const x = Number(this.v.getBigInt64(this.o, true));
    this.o += 8;
    return x;
  }
  u128() {
    const lo = this.u64();
    const hi = this.u64();
    return (hi << 64n) | lo;
  }
  key() {
    const k = new PublicKey(this.d.slice(this.o, this.o + 32));
    this.o += 32;
    return k;
  }
  bytes(n: number) {
    const b = this.d.slice(this.o, this.o + n);
    this.o += n;
    return b;
  }
}

export type RoomMemberV2 = { pubkey: PublicKey; roles: number; owner: boolean };
export type RoomStateV2 = { version: number; owner: PublicKey; revision: bigint; nextLoanIndex: number; members: RoomMemberV2[] };

export function decodeRoomStateV2(data: Uint8Array): RoomStateV2 {
  const r = new Reader(data);
  const version = r.u8();
  const owner = r.key();
  const revision = r.u64();
  const nextLoanIndex = r.u32();
  const members: RoomMemberV2[] = [];
  for (let i = 0; i < MAX_MEMBERS_V2; i++) {
    const pubkey = r.key();
    const roles = r.u8();
    const active = r.bool();
    if (active) members.push({ pubkey, roles, owner: pubkey.equals(owner) });
  }
  return { version, owner, revision, nextLoanIndex, members };
}

export const hasRole = (roles: number, role: number) => (roles & role) === role;

export type LoanTermsV2 = {
  version: number;
  originLender: PublicKey;
  currentLender: PublicKey;
  borrower: PublicKey;
  roomIndex: number;
  requestIndex: number;
  terms: TermsV2;
  collateralRequired: bigint;
  collateralLocked: bigint;
  maxLtvBps: number;
  liquidationLtvBps: number;
  revision: number;
  fundedRevision: number;
  acceptedRevision: number;
  status: LoanStatusV2;
  ledger: Ledger;
  ledgerRevision: number;
  shortfall: bigint;
  settledTs: number;
  desk: PublicKey | null;
  policyVersion: number;
  auditorHash: Uint8Array;
};

export function decodeLoanTermsV2(data: Uint8Array): LoanTermsV2 {
  const r = new Reader(data);
  const version = r.u8();
  const originLender = r.key();
  const currentLender = r.key();
  const borrower = r.key();
  const roomIndex = r.u32();
  const requestIndex = r.u32();
  const principal = r.u64();
  const interestBps = r.u16();
  const duration = r.i64();
  const early = r.u8();
  const minInterestBps = r.u16();
  const graceSeconds = r.i64();
  const lateFeeBps = r.u16();
  const annualCeilingBps = r.u16();
  const collateralRequired = r.u64();
  const collateralLocked = r.u64();
  const maxLtvBps = r.u16();
  const liquidationLtvBps = r.u16();
  const revision = r.u32();
  const fundedRevision = r.u32();
  const acceptedRevision = r.u32();
  const statusCode = r.u8();
  const startTs = r.i64();
  const ledger: Ledger = {
    outstandingPrincipal: r.u64(),
    interestAccrued: r.u64(),
    interestPaid: r.u64(),
    accrualRemainder: r.u128(),
    lastAccrualTs: r.i64(),
    lateFeeAssessed: r.u64(),
    lateFeePaid: r.u64(),
    lateFeeChecked: r.bool(),
  };
  const ledgerRevision = r.u32();
  const shortfall = r.u64();
  const settledTs = r.i64();
  const desk = r.key();
  const policyVersion = r.u32();
  const auditorHash = r.bytes(32);
  return {
    version,
    originLender,
    currentLender,
    borrower,
    roomIndex,
    requestIndex,
    terms: {
      principal,
      interestBps,
      duration,
      startTs,
      earlyRepayment: early === 1 ? EarlyRepayment.ProRata : EarlyRepayment.FullTerm,
      minInterestBps,
      graceSeconds,
      lateFeeBps,
      annualCeilingBps,
    },
    collateralRequired,
    collateralLocked,
    maxLtvBps,
    liquidationLtvBps,
    revision,
    fundedRevision,
    acceptedRevision,
    status: LOAN_STATUS_V2[statusCode as keyof typeof LOAN_STATUS_V2] ?? "draft",
    ledger,
    ledgerRevision,
    shortfall,
    settledTs,
    desk: desk.equals(PublicKey.default) ? null : desk,
    policyVersion,
    auditorHash,
  };
}

export type DeskMember = { pubkey: PublicKey; roles: number };
export type DeskStateV2 = { version: number; revision: bigint; policyVersion: number; nextLoanSeq: number; members: DeskMember[] };

export function decodeDeskState(data: Uint8Array): DeskStateV2 {
  const r = new Reader(data);
  const version = r.u8();
  const revision = r.u64();
  const policyVersion = r.u32();
  const nextLoanSeq = r.u32();
  const members: DeskMember[] = [];
  for (let i = 0; i < DESK_MEMBERS; i++) {
    const pubkey = r.key();
    const roles = r.u8();
    const active = r.bool();
    if (active) members.push({ pubkey, roles });
  }
  return { version, revision, policyVersion, nextLoanSeq, members };
}

export type DeskPolicyV2 = {
  version: number;
  publishedAt: number;
  minPrincipal: bigint;
  maxPrincipal: bigint;
  minDurationSeconds: number;
  maxDurationSeconds: number;
  maxAnnualCeilingBps: number;
  maxInterestBps: number;
  repaymentModes: number;
  maxLtvBps: number;
  maxLiquidationLtvBps: number;
  minGraceSeconds: number;
  maxLateFeeBps: number;
  auditors: PublicKey[];
};

export function decodeDeskPolicy(data: Uint8Array): DeskPolicyV2 {
  const r = new Reader(data);
  const version = r.u32();
  const publishedAt = r.i64();
  const minPrincipal = r.u64();
  const maxPrincipal = r.u64();
  const minDurationSeconds = r.i64();
  const maxDurationSeconds = r.i64();
  const maxAnnualCeilingBps = r.u16();
  const maxInterestBps = r.u16();
  const repaymentModes = r.u8();
  const maxLtvBps = r.u16();
  const maxLiquidationLtvBps = r.u16();
  const minGraceSeconds = r.i64();
  const maxLateFeeBps = r.u16();
  const count = r.u8();
  const all = Array.from({ length: MAX_AUDITORS }, () => r.key());
  return {
    version, publishedAt, minPrincipal, maxPrincipal, minDurationSeconds, maxDurationSeconds, maxAnnualCeilingBps, maxInterestBps, repaymentModes,
    maxLtvBps, maxLiquidationLtvBps, minGraceSeconds, maxLateFeeBps, auditors: all.slice(0, Math.min(count, MAX_AUDITORS)),
  };
}

/** SHA-256 of the auditor keys in order, or zeroes for none: what the borrower signs at acceptance. */
export async function auditorHash(auditors: PublicKey[]): Promise<Uint8Array> {
  if (auditors.length === 0) return new Uint8Array(32);
  const joined = new Uint8Array(32 * auditors.length);
  auditors.forEach((a, i) => joined.set(a.toBytes(), i * 32));
  return new Uint8Array(await crypto.subtle.digest("SHA-256", joined));
}

/** Policy check mirroring `PolicyArgs::allows`, so the interface explains a refusal before signing. */
export function policyProblem(p: DeskPolicyV2, t: { principal: bigint; duration: number; annualCeilingBps: number; interestBps: number; earlyRepayment: EarlyRepayment; maxLtvBps: number; liquidationLtvBps: number; graceSeconds: number; lateFeeBps: number }): string | null {
  const mode = t.earlyRepayment === EarlyRepayment.ProRata ? REPAYMENT_MODE.proRata : REPAYMENT_MODE.fullTerm;
  if (t.principal < p.minPrincipal || t.principal > p.maxPrincipal) return "The amount is outside the desk's range.";
  if (t.duration < p.minDurationSeconds || t.duration > p.maxDurationSeconds) return "The term is outside the desk's range.";
  if (t.annualCeilingBps > p.maxAnnualCeilingBps) return "The pricing ceiling is above the desk's limit.";
  if (t.interestBps > p.maxInterestBps) return "The interest is above the desk's limit.";
  if ((p.repaymentModes & mode) === 0) return "The desk does not allow this early-repayment rule.";
  if (t.maxLtvBps > p.maxLtvBps || t.liquidationLtvBps > p.maxLiquidationLtvBps) return "The LTV limits are above the desk's.";
  if (t.graceSeconds < p.minGraceSeconds) return "The grace period is shorter than the desk requires.";
  if (t.lateFeeBps > p.maxLateFeeBps) return "The late fee is above the desk's limit.";
  return null;
}
