[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
isolated_loan = "CKvMgaAJmtoUN73wDxAKvjYs2d5fcirttjjEjrV9hnef"
private_loan = "HwK4hxKqe94pLGkC9bGciENCCzvWwUAaz1mxVTDxMcK"
isolated_loan_v2 = "8hxagcQkw1Km6PWZgpA92qUnqvnFufC7tx2jvxf9Ko8m"
private_loan_v2 = "JAzy8NP6V8AGrAko8vfgrD44BDghN6eLwqB7vjuYhHNq"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
