// Replays crates/loan-core/vectors-v2.json (generated by the Rust accounting engine) against the
// TypeScript mirror in app/lib/loan-math-v2.ts. Any drift between the two fails here.
import assert from "node:assert";
import { readFileSync } from "node:fs";
import {
  applyPayment,
  chargeCeiling,
  fullTermInterest,
  graceEnd,
  liquidationSplit,
  liquidationTrigger,
  maturity,
  maxExposure,
  minInterest,
  openLedger,
  payoff,
  phase,
  pricedRecoveryFrom,
  pricedRecoverySplit,
  terminalClaimFrom,
  type Ledger,
  type TermsV2,
} from "../../app/lib/loan-math-v2";

const v = JSON.parse(readFileSync(new URL("../crates/loan-core/vectors-v2.json", import.meta.url), "utf8"));

const ledgerJson = (l: Ledger) => ({
  outstanding_principal: l.outstandingPrincipal.toString(),
  interest_accrued: l.interestAccrued.toString(),
  interest_paid: l.interestPaid.toString(),
  accrual_remainder: l.accrualRemainder.toString(),
  last_accrual_ts: l.lastAccrualTs,
  late_fee_assessed: l.lateFeeAssessed.toString(),
  late_fee_paid: l.lateFeePaid.toString(),
  late_fee_checked: l.lateFeeChecked,
});

let steps = 0;
for (const c of v.cases) {
  const t: TermsV2 = {
    principal: BigInt(c.terms.principal),
    interestBps: c.terms.interest_bps,
    duration: c.terms.duration,
    startTs: c.terms.start_ts,
    earlyRepayment: c.terms.early_repayment,
    minInterestBps: c.terms.min_interest_bps,
    graceSeconds: c.terms.grace_seconds,
    lateFeeBps: c.terms.late_fee_bps,
    annualCeilingBps: c.terms.annual_ceiling_bps,
  };
  const d = c.derived;
  assert.deepEqual(
    {
      maturity: maturity(t), grace_end: graceEnd(t), priced_recovery_from: pricedRecoveryFrom(t), terminal_claim_from: terminalClaimFrom(t),
      full_term_interest: fullTermInterest(t).toString(), charge_ceiling: chargeCeiling(t).toString(), min_interest: minInterest(t).toString(), max_exposure: maxExposure(t).toString(),
    },
    d,
    c.name,
  );
  let l = openLedger(t);
  for (const s of c.steps) {
    steps++;
    if (s.op === "payoff") assert.equal(payoff(t, l, s.now).toString(), s.expect, `${c.name} payoff @${s.now}`);
    else if (s.op === "phase") assert.equal(phase(t, s.now), s.expect, `${c.name} phase @${s.now}`);
    else {
      const amount = BigInt(s.amount);
      const [n, p] = applyPayment(t, l, s.now, amount);
      l = n;
      assert.deepEqual(
        { used: p.used.toString(), interest: p.interest.toString(), late_fee: p.lateFee.toString(), principal: p.principal.toString(), adjustment: p.adjustment.toString(), closed: p.closed, ledger: ledgerJson(l) },
        s.expect,
        `${c.name} pay @${s.now}`,
      );
    }
  }
}
for (const c of v.triggers) assert.equal(liquidationTrigger(c.spot, c.ema, c.threshold), c.expect, JSON.stringify(c));
for (const c of v.splits) {
  const f = c.kind === "liquidation" ? liquidationSplit : pricedRecoverySplit;
  const s = f(BigInt(c.payoff), BigInt(c.lamports), BigInt(c.value));
  assert.deepEqual({ to_recipient: s.toRecipient.toString(), to_borrower: s.toBorrower.toString(), shortfall: s.shortfall.toString() }, { to_recipient: c.to_recipient, to_borrower: c.to_borrower, shortfall: c.shortfall }, JSON.stringify(c));
}
console.log(`loan-math v2 parity passed: ${v.cases.length} cases, ${steps} steps, ${v.triggers.length} triggers, ${v.splits.length} splits`);
