//! Byte fixtures of the ER-only V2 records, for the TypeScript codec (app/lib/private/v2-codec.ts).
//! Regenerate with `REGENERATE_FIXTURE=1 cargo test --test codec_fixture`; every other run checks it.
use anchor_lang::prelude::Pubkey;
use anchor_lang::AnchorSerialize;
use private_loan_v2::desk::{DeskMember, DeskPolicy, DeskState, PolicyArgs, DESK_ADMIN, DESK_AUDITOR, DESK_LENDER, DESK_MEMBERS, MODE_PRO_RATA};
use private_loan_v2::loan::{LedgerState, LoanTerms, STATUS_ACTIVE};
use private_loan_v2::room::{MemberSlot, RoomState, MAX_MEMBERS, ROLE_BORROWER, ROLE_LENDER, ROLE_VIEWER};
use serde_json::{json, Value};

fn key(n: u8) -> Pubkey {
    Pubkey::new_from_array([n; 32])
}

fn hex(v: &impl AnchorSerialize) -> String {
    let mut out = Vec::new();
    v.serialize(&mut out).unwrap();
    out.iter().map(|b| format!("{b:02x}")).collect()
}

fn build() -> Value {
    let mut members = [MemberSlot::default(); MAX_MEMBERS];
    members[0] = MemberSlot { pubkey: key(1), role: ROLE_VIEWER, active: true };
    members[1] = MemberSlot { pubkey: key(2), role: ROLE_LENDER | ROLE_BORROWER, active: true };
    members[2] = MemberSlot { pubkey: key(3), role: ROLE_LENDER, active: false };
    let room = RoomState { version: 2, owner: key(1), revision: 7, next_loan_index: 3, members };

    let terms = LoanTerms {
        version: 2, origin_lender: key(4), current_lender: key(5), borrower: key(6), room_index: 2, request_index: 9,
        principal: 100_000_000, interest_bps: 500, duration_seconds: 2_592_000, early_repayment: 1, min_interest_bps: 2_500,
        grace_seconds: 86_400, late_fee_bps: 100, annual_ceiling_bps: 10_000, collateral_required: 1_020_000_000,
        collateral_locked: 1_520_000_000, max_ltv_bps: 7_000, liquidation_ltv_bps: 8_000, revision: 3, funded_revision: 3,
        accepted_revision: 3, status: STATUS_ACTIVE, start_ts: 1_800_000_000,
        ledger: LedgerState {
            outstanding_principal: 71_666_666, interest_accrued: 12, interest_paid: 1_666_666, accrual_remainder: 123_456_789_012_345_678_901,
            last_accrual_ts: 1_800_864_000, late_fee_assessed: 0, late_fee_paid: 0, late_fee_checked: false,
        },
        ledger_revision: 4, shortfall: 0, settled_ts: 0, desk: key(7), policy_version: 2, auditor_hash: [9; 32],
    };

    let mut dm = [DeskMember::default(); DESK_MEMBERS];
    dm[0] = DeskMember { pubkey: key(1), roles: DESK_ADMIN, active: true };
    dm[1] = DeskMember { pubkey: key(4), roles: DESK_LENDER, active: true };
    dm[2] = DeskMember { pubkey: key(8), roles: DESK_AUDITOR, active: true };
    let desk = DeskState { version: 1, revision: 5, policy_version: 2, next_loan_seq: 11, members: dm };

    let policy = DeskPolicy {
        version: 2,
        published_at: 1_800_000_100,
        args: PolicyArgs {
            min_principal: 1_000_000, max_principal: 500_000_000, min_duration_seconds: 86_400, max_duration_seconds: 7_776_000,
            max_annual_ceiling_bps: 3_000, max_interest_bps: 1_000, repayment_modes: MODE_PRO_RATA, max_ltv_bps: 6_500,
            max_liquidation_ltv_bps: 8_000, min_grace_seconds: 86_400, max_late_fee_bps: 100, auditor_count: 1,
            auditors: [key(8), Pubkey::default(), Pubkey::default(), Pubkey::default()],
        },
    };

    json!({
        "note": "Generated by programs/private_loan_v2/tests/codec_fixture.rs. Keys are 32 repeated bytes of the number shown.",
        "roomState": { "hex": hex(&room), "owner": 1, "revision": "7", "nextLoanIndex": 3, "members": [[1, ROLE_VIEWER], [2, ROLE_LENDER | ROLE_BORROWER]] },
        "loanTerms": {
            "hex": hex(&terms), "originLender": 4, "currentLender": 5, "borrower": 6, "roomIndex": 2, "requestIndex": 9, "principal": "100000000",
            "status": STATUS_ACTIVE, "collateralLocked": "1520000000", "outstandingPrincipal": "71666666", "accrualRemainder": "123456789012345678901",
            "ledgerRevision": 4, "desk": 7, "policyVersion": 2, "auditorHashByte": 9,
        },
        "deskState": { "hex": hex(&desk), "policyVersion": 2, "nextLoanSeq": 11, "members": [[1, DESK_ADMIN], [4, DESK_LENDER], [8, DESK_AUDITOR]] },
        "deskPolicy": { "hex": hex(&policy), "version": 2, "maxAnnualCeilingBps": 3000, "maxPrincipal": "500000000", "auditors": [8] },
    })
}

#[test]
fn codec_fixture_matches() {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/codec-fixture.json");
    let built = build();
    if std::env::var("REGENERATE_FIXTURE").is_ok() {
        std::fs::write(path, serde_json::to_string_pretty(&built).unwrap() + "\n").unwrap();
    }
    let stored: Value = serde_json::from_str(&std::fs::read_to_string(path).expect("run with REGENERATE_FIXTURE=1 once")).unwrap();
    assert_eq!(stored, built);
}
